#!/bin/bash
#exit 0

if [ $# -ne 4 ]
then
	echo "Usage: $0 host server port size"
	exit 1
fi

host=$1
server=$2
port=$3
size=$4

# UDP
#cmd="iperf -u -c $server -b 100M -p $port -n $size --reportstyle c"

#TCP
cmd="iperf -c $server -p $port -n $size --reportstyle c"

sufflix=`echo $host $cmd | tr ' ' '-'`
stdout="/tmp/iperf/temp-stdout-"`date +%s`"-"$sufflix".txt"
stderr="/tmp/iperf/temp-stderr-"`date +%s`"-"$sufflix".txt"
other="/tmp/iperf/iperf-"`date +%s`"-"$sufflix".txt"
touch $stderr $stdout $other

echo `date`" - start" > $other
#cmd="tcp-client $server $port $size"
eval $cmd 2> $stderr > $stdout
echo `date`" - after first run" >> $other

error=`wc -l $stderr | cut -d' ' -f1`
output=`wc -l $stdout | cut -d' ' -f1`
#cat $stdout >> $other
cat $stderr >> $other
echo `date`" - error=$error, output=$output" >> $other

while [ "$output" -eq 0 ]
do
	echo `date`" - run again start" >> $other
	eval $cmd 2> $stderr > $stdout
	error=`wc -l $stderr | cut -d' ' -f1`
	output=`wc -l $stdout | cut -d' ' -f1`
	#cat $stdout >> $other
	cat $stderr >> $other
	echo `date`" - run again end" >> $other
done
echo "OUTPUT="`cat $stdout` >> $other
echo `date`" - end" >> $other
rm -f $stdout $stderr
exit 0

